// Default dataset for the no-backend demo. The consumer inventory and threat
// coverage are REAL Keyway output (see ./seed, generated by `keyway discover` over
// bench/oss/manifests and `keyway threats coverage`), not fabricated. Drift and
// probe history are shown at their honest baseline (empty) until the app runs live
// against a backend. Force the live API with localStorage `keyway.live=1`.
import { computeBlast } from "../lib/blast";
import consumersSeed from "./seed/consumers.json";
import coverageSeed from "./seed/coverage.json";
import type {
  AgentFinding,
  AgentInspectRequest,
  AgentInspectResult,
  BlastRadiusResult,
  CanaryStatus,
  ChangeEvent,
  Consumer,
  CoverageResponse,
  IssuerInfo,
  Key,
  ProbeResult,
  SnapshotResponse,
  ThreatCoverage,
} from "./types";

export const coverage = (): CoverageResponse => {
  const cs = consumers();
  const resolved = cs.filter((c) => (c.confidence?.overall ?? 0) >= 1).length;
  const low = cs.filter((c) => { const o = c.confidence?.overall ?? 0; return o > 0 && o < 1; }).length;
  const unresolved = cs.filter((c) => (c.expects?.issuers?.length ?? 0) === 0).length;
  return { total: cs.length, resolved, low_confidence: low, unresolved };
};

export const latestSnapshot = (): SnapshotResponse => ({
  version_id: "baseline",
  hash: "baseline",
  is_baseline: true,
});

export const consumers = (): Consumer[] => consumersSeed as unknown as Consumer[];

export const consumerProbes = (_stableId: string): ProbeResult[] => [];

export const blastRadius = (proposal: BlastRadiusResult["proposal"]): BlastRadiusResult =>
  computeBlast(consumers(), proposal);

// --- interactive mocks (so the demo works with no backend) ---

// In-memory canary key state per issuer, mutated by announce/promote so the
// sample UI behaves like the real lifecycle.
const canaryState: Record<string, Key[]> = {
  default: [
    {
      kid: "rsa-2025-06",
      alg: "RS256",
      use: "sig",
      status: "active",
      first_seen_in_jwks: new Date(Date.now() - 40 * 86400_000).toISOString(),
      in_signing_use_since: new Date(Date.now() - 40 * 86400_000).toISOString(),
    },
  ],
};

let mockKidSeq = 100;

export const issuers = (): IssuerInfo[] => [
  {
    id: "default",
    name: "default",
    type: "generic_oidc",
    issuer_url: "https://kc/realms/main",
    jwks_uri: "https://kc/realms/main/protocol/openid-connect/certs",
    keys: canaryState["default"],
  },
];

export const canaryStatus = (issuerId: string): CanaryStatus => {
  const keys = canaryState[issuerId] ?? [];
  const announced = keys.find((k) => k.status === "announced");
  return { issuer: issuerId, keys, announced_kid: announced?.kid ?? "" };
};

export const canaryAnnounce = (issuerId: string, alg: string): Key => {
  const key: Key = {
    kid: `rsa-2026-${mockKidSeq++}`,
    alg: alg || "RS256",
    use: "sig",
    status: "announced",
    first_seen_in_jwks: new Date().toISOString(),
  };
  canaryState[issuerId] = [...(canaryState[issuerId] ?? []), key];
  return key;
};

// Promote flips the announced key to active signing and moves the prior active
// key to retiring — mirroring the real KeyStatus lifecycle so the demo advances.
export const canaryPromote = (issuerId: string, kid: string): { promoted: string } => {
  const keys = canaryState[issuerId] ?? [];
  canaryState[issuerId] = keys.map((k) => {
    if (k.kid === kid) return { ...k, status: "active", in_signing_use_since: new Date().toISOString() };
    if (k.status === "active") return { ...k, status: "retiring" };
    return k;
  });
  return { promoted: kid };
};

export const createSnapshot = (): SnapshotResponse => ({
  version_id: `v-${Date.now()}`,
  hash: Array.from({ length: 64 }, () => "0123456789abcdef"[Math.floor(Math.random() * 16)]).join(""),
  is_baseline: false,
});

export const runProbes = (consumerIds?: string[]): { run_id: string; results: ProbeResult[] } => {
  const targets = (consumers().filter((c) => c.probeable) ?? []).filter(
    (c) => !consumerIds || consumerIds.length === 0 || consumerIds.includes(c.stable_id),
  );
  const results: ProbeResult[] = [];
  const probes = [
    { probe_id: "alg_none", passed: true, status: 401 },
    { probe_id: "alg_confusion", passed: true, status: 401 },
    { probe_id: "tampered_signature", passed: true, status: 401 },
    { probe_id: "expired", passed: true, status: 401 },
    { probe_id: "wrong_audience", passed: true, status: 403 },
    { probe_id: "wrong_issuer", passed: true, status: 401 },
    { probe_id: "valid_token", passed: true, status: 200 },
  ];
  for (const c of targets) {
    for (let i = 0; i < probes.length; i++) {
      const p = probes[i];
      // legacy-reporting fails the alg_none probe (a real finding) in the demo.
      const passed = c.name === "legacy-reporting" && p.probe_id === "alg_none" ? false : p.passed;
      results.push({
        id: `${c.stable_id}-${p.probe_id}`,
        probe_id: p.probe_id,
        consumer_id: c.stable_id,
        endpoint_url: "https://svc.internal/healthz",
        status_code: passed ? p.status : 200,
        latency_ms: 8 + i * 2,
        passed,
        raw_response: "",
        run_at: new Date().toISOString(),
      });
    }
  }
  return { run_id: `run-${Date.now()}`, results };
};

// A freshly-discovered inventory sits at baseline — no drift yet (Keyway's model:
// first run = baseline, zero alerts). Real change history appears once the app runs
// live against a backend over time.
export const changes = (): ChangeEvent[] => [];

/* ── Threat coverage (mock mirrors `keyway threats coverage`) ─────────── */

export const threatCoverage = (): ThreatCoverage => coverageSeed as unknown as ThreatCoverage;


/* ── Agent-token inspection (mock mirrors internal/agentauth) ─────────── */

function decodeClaims(token: string): Record<string, unknown> | null {
  const parts = token.trim().split(".");
  if (parts.length < 2) return null;
  try {
    let b = parts[1].replace(/-/g, "+").replace(/_/g, "/");
    while (b.length % 4) b += "=";
    return JSON.parse(decodeURIComponent(escape(atob(b))));
  } catch {
    return null;
  }
}

const omnibus = new Set(["*", "admin", "root", "superuser", "full_access", "full-access", "all"]);

export const agentInspect = (req: AgentInspectRequest): AgentInspectResult => {
  const claims = decodeClaims(req.token);
  if (!claims) return { findings: [{ threat_id: "—", severity: "info", message: "not a JWT (want at least header.payload)" }], count: 1 };
  const f: AgentFinding[] = [];

  if (req.audience) {
    const aud = claims["aud"];
    const list = Array.isArray(aud) ? aud : typeof aud === "string" ? [aud] : [];
    if (!aud || list.length === 0)
      f.push({ threat_id: "MCP-02", severity: "high", message: "token carries no audience — it is not bound to any resource (RFC 8707/9728)" });
    else if (!list.includes(req.audience))
      f.push({ threat_id: "MCP-01", severity: "critical", message: `audience does not include the resource "${req.audience}" — token could be replayed or passed through` });
  }
  if (req.require_delegation && claims["act"] == null)
    f.push({ threat_id: "DEL-01", severity: "high", message: "on-behalf-of token is missing the act claim — the delegation chain is unverifiable (RFC 8693)" });

  // DEL-02: a present act chain that is malformed (a link with no sub) is
  // unverifiable — mirrors internal/agentauth inspectActChain.
  if (claims["act"] != null) {
    let node: unknown = claims["act"];
    let malformed = false;
    while (node != null) {
      if (typeof node !== "object" || Array.isArray(node)) { malformed = true; break; }
      const sub = (node as Record<string, unknown>)["sub"];
      if (typeof sub !== "string" || sub.trim() === "") { malformed = true; break; }
      node = (node as Record<string, unknown>)["act"];
    }
    if (malformed)
      f.push({ threat_id: "DEL-02", severity: "high", message: "delegation act chain has an actor with no sub — an unverifiable link, so a hop cannot independently validate the delegation (RFC 8693)" });
  }

  const scopes: string[] = [];
  if (typeof claims["scope"] === "string") scopes.push(...(claims["scope"] as string).split(/\s+/).filter(Boolean));
  const scp = claims["scp"];
  if (Array.isArray(scp)) scopes.push(...scp.filter((x): x is string => typeof x === "string"));
  const allow = new Set(req.allowed_scopes ?? []);
  for (const s of scopes) {
    const low = s.toLowerCase();
    if (omnibus.has(low) || s.endsWith(":*") || s.endsWith(".*") || low.startsWith("admin:"))
      f.push({ threat_id: "SCOPE-01", severity: "high", message: `over-broad scope "${s}" — grant least privilege, not omnibus access` });
    else if (allow.size > 0 && !allow.has(s))
      f.push({ threat_id: "SCOPE-01", severity: "medium", message: `scope "${s}" is beyond the declared allowlist` });
  }

  const exp = claims["exp"];
  if (typeof exp !== "number") f.push({ threat_id: "SCOPE-02", severity: "high", message: "token has no exp — a non-expiring agent credential" });
  else if (req.max_lifetime_seconds && typeof claims["iat"] === "number") {
    const life = exp - (claims["iat"] as number);
    if (life > req.max_lifetime_seconds)
      f.push({ threat_id: "SCOPE-02", severity: "medium", message: `token lifetime ${Math.round(life / 60)}m exceeds the maximum ${Math.round(req.max_lifetime_seconds / 60)}m` });
  }
  return { findings: f, count: f.length };
};
