apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata: { name: api-a, namespace: prod }
spec:
  selector: { matchLabels: { app: api-a } }
  jwtRules:
    - issuer: "https://kc/realms/partner"
      audiences: ["api-a"]
    - issuer: "https://kc/realms/main"
      audiences: ["api-a"]
