package realworld

import (
	"fmt"
	"strings"
)

// MarkdownReport runs every case and renders a cited, GitHub-friendly report of
// whether Keyway detects each documented real-world risk.
func MarkdownReport() (md string, detected, total int) {
	cases := Cases()
	var rows strings.Builder
	for _, c := range cases {
		res := c.Run()
		total++
		mark := "❌ **missed**"
		if res.Detected {
			detected++
			mark = "✅ flagged"
		}
		fmt.Fprintf(&rows, "| %s | %s | [%s](%s) | `%s` | %s |\n",
			c.ID, c.Title, c.Reference, c.Source, c.Mechanism, mark)
	}

	pct := 0
	if total > 0 {
		pct = detected * 100 / total
	}

	var b strings.Builder
	b.WriteString("# Real-world risk validation\n\n")
	b.WriteString("> Does Keyway actually catch the JWT/JWKS risks that have bitten real projects?\n")
	b.WriteString("> Each row below **reproduces the exact failure mode from a cited public source**\n")
	b.WriteString("> (a CVE, a GitHub issue, a spec rule) and checks whether Keyway flags it.\n\n")
	fmt.Fprintf(&b, "**Result: Keyway detected %d of %d documented risks (%d%%).**\n\n", detected, total, pct)
	b.WriteString("This runs in CI (`go test ./bench/realworld/...`), so the guarantee can't silently rot.\n\n")

	b.WriteString("| # | Risk | Source | Keyway check | Result |\n")
	b.WriteString("|---|---|---|---|---|\n")
	b.WriteString(rows.String())
	b.WriteString("\n")

	b.WriteString("## How each case is validated\n\n")
	b.WriteString("- **Token-level risks (RW-01…RW-07)** — a minimal HTTP service is stood up that\n")
	b.WriteString("  reproduces the vulnerable behavior (e.g. accepting an `alg=none` token, or\n")
	b.WriteString("  verifying an `HS256` token with the RSA *public* key). Keyway's probe engine\n")
	b.WriteString("  fires its synthetic attack token at it; a probe that the service wrongly\n")
	b.WriteString("  accepts is reported as a finding. If the server returns `200` to the attack,\n")
	b.WriteString("  Keyway flags it.\n")
	b.WriteString("- **Rotation risk (RW-08)** — reproduces OpenFGA's configuration (the\n")
	b.WriteString("  `MicahParks/keyfunc` v1.x default `RefreshUnknownKID=false`) and asks Keyway's\n")
	b.WriteString("  blast-radius engine what happens on a key rotation. Keyway answers\n")
	b.WriteString("  **will_break** — *before* the rotation — from library defaults alone, with\n")
	b.WriteString("  zero probes. That is exactly the outage described in the cited issue.\n\n")

	b.WriteString("## Honesty notes\n\n")
	b.WriteString("- These are **reproductions** of the cited failure modes, not live scans of the\n")
	b.WriteString("  named projects. The citation identifies the real-world class of bug; the code\n")
	b.WriteString("  next to it recreates that class so the detection can be checked deterministically.\n")
	b.WriteString("- Sources are the authoritative record for each class: NVD for CVEs, the project's\n")
	b.WriteString("  own issue tracker for the rotation outage, and RFC 8725 (JWT BCP) / CWE for the\n")
	b.WriteString("  claim-validation classes.\n\n")
	b.WriteString("_Generated by `keyway bench --realworld` (`bench/realworld`)._\n")

	return b.String(), detected, total
}
